stages:

  data_cleaning:
    cmd: hrs_env/bin/python src/data/data_cleaning.py
    deps:
    - src/data/data_cleaning.py
    - data/raw
    params:
    - data_cleaning.max_features
    outs:
    - data/processed
    - models

  content_sys:
    cmd: hrs_env/bin/python src/features/content_sys.py
    deps:
    - src/features/content_sys.py
    - data/processed
    # outs:
    # - data/FE

  collaborative_sys:
    cmd: hrs_env/bin/python src/features/collaborative_sys.py
    deps:
    - src/features/collaborative_sys.py
    - data/processed
    # outs:
    # - data/FE

  # model_building:
  #   cmd: python src/models/model_building.py
  #   deps:
  #   - src/models/model_building.py
  #   - data/FE
  #   params:
  #   - model_building.learning_rate
  #   - model_building.n_estimators
  #   outs:

  # model_evaluation:
  #   cmd: python src/visualization/model_evaluation.py
  #   deps:
  #   - data/FE
  #   - models
  #   - src/visualization/model_evaluation.py
  #   metrics:
  #   - reports/metrics/metrics.json:
  #       cache: false
